//
//  signinProtocols.swift
//  Viper2
//
//  Created Henry on 9/9/17.
//  Copyright © 2017 Henry Tsai. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol signinWireframeProtocol: class {

}
//MARK: Presenter -
protocol signinPresenterProtocol: class {

}

//MARK: Interactor -
protocol signinInteractorProtocol: class {

  var presenter: signinPresenterProtocol?  { get set }
}

//MARK: View -
protocol signinViewProtocol: class {

  var presenter: signinPresenterProtocol?  { get set }
}
