//
//  signinRouter.swift
//  Viper2
//
//  Created Henry on 9/9/17.
//  Copyright © 2017 Henry Tsai. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class signinRouter: signinWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = signinViewController(nibName: nil, bundle: nil)
        let interactor = signinInteractor()
        let router = signinRouter()
        let presenter = signinPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
