//
//  signinViewController.swift
//  Viper2
//
//  Created Henry on 9/9/17.
//  Copyright © 2017 Henry Tsai. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class signinViewController: UIViewController, signinViewProtocol {

	var presenter: signinPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
